// apps/demo-react/src/app/app.tsx
import React, { useState } from 'react';
import { DocumentViewer } from '@documentviewer/ui-react';
import { handleFileUpload, viewers, ViewerType } from '@documentviewer/data';
import './app.module.scss';

export function App() {
  const [selectedViewer, setSelectedViewer] = useState(viewers[0]);
  const [selectedDoc, setSelectedDoc] = useState(viewers[0].docs[0]);
  const [url, setUrl] = useState('');

  const handleChange = (e) => {
    setUrl(e.target.value);
  };

  const getDocExtension = (doc: string) => {
    const splittedDoc = doc.split('.');
    return splittedDoc[splittedDoc.length - 1];
  };

  const selectViewer = (viewerName: ViewerType) => {
    if (viewerName !== selectViewer.name) {
      const viewer = viewers.find((v) => v.name === viewerName);
      setSelectedViewer(viewer);
      setSelectedDoc(viewer.docs[0]);
    }
  };

  const handleFiles = async (fileInput: any) => {
    this.selectedDoc = await handleFileUpload(fileInput);
  };

  return (
    <div className="text-center">
      <div className="d-flex">
        {viewers.map((viewer) => {
          return (
            <button
              key={viewer.name}
              className={
                (selectedViewer.name === viewer.name ? 'active' : '') +
                ' btn btn-outline-primary m-2'
              }
              onClick={() => selectViewer(viewer.name)}
            >
              {viewer.name}
            </button>
          );
        })}
      </div>
      <div className="d-flex">
        {selectedViewer.docs.map((doc) => {
          return (
            <div key={doc} className="d-flex">
              <button
                className={
                  (selectedDoc === doc ? 'active' : '') +
                  ' btn btn-outline-secondary m-2'
                }
                onClick={() => setSelectedDoc(doc)}
              >
                {getDocExtension(doc)}
              </button>
            </div>
          );
        })}
        {selectedViewer.custom ? (
          <>
            <input
              onChange={handleChange}
              className="form-control w-100 m-2"
              type="text"
              placeholder="your document url"
            />
            <button
              className="btn btn-outline-secondary m-2"
              onClick={() => setSelectedDoc(url)}
            >
              Go
            </button>
          </>
        ) : null}
        {selectedViewer.acceptedUploadTypes ? (
          <input
            type="file"
            id="input"
            accept={selectedViewer.acceptedUploadTypes}
            onChange={handleFiles}
          />
        ) : null}
      </div>

      <DocumentViewer
        queryParams="hl=Nl"
        url={selectedDoc}
        viewerUrl={selectedViewer.viewerUrl}
        viewer={selectedViewer.name}
      ></DocumentViewer>
    </div>
  );
}

export default App;

// demo/app/app.component.ts
import { Component, ViewChild } from '@angular/core';
import { viewerType } from 'modules/document-viewer.component';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styles: []
})
export class AppComponent {
  viewers: { name: viewerType, docs: string[], custom: boolean, acceptedUploadTypes: string, viewerUrl?: string }[] = [
    {
      name: 'google', docs: [
        'https://file-examples.com/wp-content/uploads/2017/02/file-sample_100kB.docx',
        'https://file-examples.com/wp-content/uploads/2017/02/file_example_XLSX_10.xlsx',
        'https://file-examples.com/wp-content/uploads/2017/10/file_example_TIFF_1MB.tiff',
        'https://file-examples.com/wp-content/uploads/2017/10/file-sample_150kB.pdf',
        'https://file-examples.com/wp-content/uploads/2017/08/file_example_PPT_250kB.ppt'
      ], custom: true, acceptedUploadTypes: null
    },
    {
      name: 'office', docs: [
        'https://file-examples.com/wp-content/uploads/2017/02/file-sample_100kB.docx',
        'https://file-examples.com/wp-content/uploads/2017/02/file_example_XLSX_10.xlsx',
        'https://file-examples.com/wp-content/uploads/2017/10/file_example_TIFF_1MB.tiff',
        'https://file-examples.com/wp-content/uploads/2017/10/file-sample_150kB.pdf',
        'https://file-examples.com/wp-content/uploads/2017/08/file_example_PPT_250kB.ppt'
      ], custom: true, acceptedUploadTypes: null
    },
    {
      name: 'mammoth', docs: [
        `${window.location.href}/assets/file-sample_100kB.docx`
      ], custom: false, acceptedUploadTypes: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    },
    {
      name: 'pdf', docs: [
        `${window.location.href}/assets/file-sample_150kB.pdf`
      ], custom: false, acceptedUploadTypes: 'application/pdf'
    },
    {
      name: 'url', docs: [
        `https://docs.google.com/document/d/e/2PACX-1vRs3gemrszDinuGJCi_wO2m5XVP1q2SlRhxM8PAUYc3wu9LFsvteny7l6Rkp695-ruhfn3gWXV03yXC/pub?embedded=true`
      ], custom: false, acceptedUploadTypes: null
    }
  ];
  selectedViewer = this.viewers[0];
  selectedDoc = this.selectedViewer.docs[0];

  constructor() { }
  selectViewer(viewerName: viewerType) {
    if (viewerName !== this.selectViewer.name) {
      this.selectedViewer = this.viewers.find(v => v.name === viewerName);
      this.selectedDoc = this.selectedViewer.docs[0];
    }
  }

  getDocExtension(doc: string) {
    const splittedDoc = doc.split('.');
    return splittedDoc[splittedDoc.length - 1];
  }

  handleFiles(fileInput: any) {
    if (fileInput.target.files && fileInput.target.files[0]) {
      const reader = new FileReader();

      reader.onload = (e: any) => {
        this.selectedDoc = e.target.result;
      };
      reader.readAsDataURL(fileInput.target.files[0]);
    }
  }
}

<div style="text-align:center">
    <div class="d-flex">
        <button
            *ngFor="let viewer of viewers"
            [class.active]="selectedViewer.name === viewer.name"
            class="btn btn-outline-primary m-2"
            (click)="selectViewer(viewer.name)"
        >{{viewer.name}}</button>
    </div>
    <div class="d-flex">
        <button *ngFor="let doc of selectedViewer.docs" [class.active]="selectedDoc === doc" class="btn btn-outline-secondary m-2"
         (click)="selectedDoc = doc">{{getDocExtension(doc)}}</button>
        <ng-container *ngIf="selectedViewer.custom">
            <input
                class="form-control w-100 m-2"
                type="text"
                placeholder="your document url"
                #input
            >
            <button
                class="btn btn-outline-secondary m-2"
                (click)="selectedDoc = input.value;"
            >Go</button>
        </ng-container>
        <ng-container *ngIf="selectedViewer.acceptedUploadTypes">
            <input type="file" id="input" [accept]="selectedViewer.acceptedUploadTypes" (change)="handleFiles($event)">
        </ng-container>
    </div>
    <ngx-doc-viewer
        queryParams="hl=Nl"
        [url]="selectedDoc"
        [viewerUrl]="selectedViewer.viewerUrl"
        [viewer]="selectedViewer.name"
        style="width:100%;height:80vh;"
    ></ngx-doc-viewer>
</div>
