// apps/demo-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { handleFileUpload, viewers, ViewerType } from '@documentviewer/data';
@Component({
  selector: 'documentviewer-root',
  templateUrl: 'app.component.html',
  styles: []
})
export class AppComponent {
  viewers = viewers;
  selectedViewer = this.viewers[0];
  selectedDoc = this.selectedViewer.docs[0];

  selectViewer(viewerName: ViewerType) {
    if (viewerName !== this.selectViewer.name) {
      this.selectedViewer = this.viewers.find(v => v.name === viewerName);
      this.selectedDoc = this.selectedViewer.docs[0];
    }
  }

  getDocExtension(doc: string) {
    const splittedDoc = doc.split('.');
    return splittedDoc[splittedDoc.length - 1];
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  async handleFiles(fileInput: any) {
    this.selectedDoc = await handleFileUpload(fileInput);
  }

}

<div style="text-align: center">
  <div class="d-flex">
    <button
      *ngFor="let viewer of viewers"
      [class.active]="selectedViewer.name === viewer.name"
      class="btn btn-outline-primary m-2"
      (click)="selectViewer(viewer.name)"
    >
      {{ viewer.name }}
    </button>
  </div>
  <div class="d-flex">
    <button
      *ngFor="let doc of selectedViewer.docs"
      [class.active]="selectedDoc === doc"
      class="btn btn-outline-secondary m-2"
      (click)="selectedDoc = doc"
    >
      {{ getDocExtension(doc) }}
    </button>
    <ng-container *ngIf="selectedViewer.custom">
      <input
        class="form-control w-100 m-2"
        type="text"
        placeholder="your document url"
        #input
      />
      <button
        class="btn btn-outline-secondary m-2"
        (click)="selectedDoc = input.value"
      >
        Go
      </button>
    </ng-container>
    <ng-container *ngIf="selectedViewer.acceptedUploadTypes">
      <input
        type="file"
        id="input"
        [accept]="selectedViewer.acceptedUploadTypes"
        (change)="handleFiles($event)"
      />
    </ng-container>
  </div>
  <ngx-doc-viewer
    queryParams="hl=Nl"
    [url]="selectedDoc"
    [viewerUrl]="selectedViewer.viewerUrl"
    [viewer]="selectedViewer.name"
    style="width: 100%; height: 80vh"
  ></ngx-doc-viewer>
</div>

// apps/demo-react/src/app/app.tsx
import React, { useState } from 'react';
import { DocumentViewer } from '@documentviewer/ui-react';
import { handleFileUpload, viewers, ViewerType } from '@documentviewer/data';
import './app.module.scss';

export function App() {
  const [selectedViewer, setSelectedViewer] = useState(viewers[0]);
  const [selectedDoc, setSelectedDoc] = useState(viewers[0].docs[0]);
  const [url, setUrl] = useState('');

  const handleChange = (e) => {
    setUrl(e.target.value);
  };

  const getDocExtension = (doc: string) => {
    const splittedDoc = doc.split('.');
    return splittedDoc[splittedDoc.length - 1];
  };

  const selectViewer = (viewerName: ViewerType) => {
    if (viewerName !== selectViewer.name) {
      const viewer = viewers.find((v) => v.name === viewerName);
      setSelectedViewer(viewer);
      setSelectedDoc(viewer.docs[0]);
    }
  };

  const handleFiles = async (fileInput: any) => {
    this.selectedDoc = await handleFileUpload(fileInput);
  };

  return (
    <div className="text-center">
      <div className="d-flex">
        {viewers.map((viewer) => {
          return (
            <button
              key={viewer.name}
              className={
                (selectedViewer.name === viewer.name ? 'active' : '') +
                ' btn btn-outline-primary m-2'
              }
              onClick={() => selectViewer(viewer.name)}
            >
              {viewer.name}
            </button>
          );
        })}
      </div>
      <div className="d-flex">
        {selectedViewer.docs.map((doc) => {
          return (
            <div key={doc} className="d-flex">
              <button
                className={
                  (selectedDoc === doc ? 'active' : '') +
                  ' btn btn-outline-secondary m-2'
                }
                onClick={() => setSelectedDoc(doc)}
              >
                {getDocExtension(doc)}
              </button>
            </div>
          );
        })}
        {selectedViewer.custom ? (
          <>
            <input
              onChange={handleChange}
              className="form-control w-100 m-2"
              type="text"
              placeholder="your document url"
            />
            <button
              className="btn btn-outline-secondary m-2"
              onClick={() => setSelectedDoc(url)}
            >
              Go
            </button>
          </>
        ) : null}
        {selectedViewer.acceptedUploadTypes ? (
          <input
            type="file"
            id="input"
            accept={selectedViewer.acceptedUploadTypes}
            onChange={handleFiles}
          />
        ) : null}
      </div>

      <DocumentViewer
        queryParams="hl=Nl"
        url={selectedDoc}
        viewerUrl={selectedViewer.viewerUrl}
        viewer={selectedViewer.name}
      ></DocumentViewer>
    </div>
  );
}

export default App;
