// libs/ui-angular/src/lib/document-viewer.component.ts
import { Component, Input, NgZone, OnDestroy, OnChanges, SimpleChanges, Output, ViewChildren, QueryList, ElementRef } from '@angular/core';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';
import { Subscription } from 'rxjs';
import { EventEmitter } from '@angular/core';
import { getDocxToHtml, getViewerDetails, googleCheckSubscription } from '@documentviewer/data';
// eslint-disable-next-line @typescript-eslint/naming-convention
export type viewerType = 'google' | 'office' | 'mammoth' | 'pdf' | 'url';
@Component({
    // eslint-disable-next-line @angular-eslint/component-selector
    selector: 'ngx-doc-viewer',
    templateUrl: 'document-viewer.component.html',
    styles: [`:host {
        display: block;
    }
    .container {
        width: 100%;
        height: 100%;
        position: relative;
    }
    .overlay-popout-google {
        width: 40px;
        height: 40px;
        right: 26px;
        top: 11.5px;
        position: absolute;
        z-index: 1000;
    }
    .overlay-popout-office {
        width: 100px;
        height: 20px;
        right: 0;
        bottom: 0;
        position: absolute;
        z-index: 1000;
    }
    .overlay-full {
        width: 100%;
        height: 100%;
        right: 0;
        top: 0;
        position: absolute;
        z-index: 1000;
    }
    iframe {
        width: 100%;
        height: 100%;
    }
    `]
})
export class NgxDocViewerComponent implements OnChanges, OnDestroy {
    @Output() loaded: EventEmitter<void> = new EventEmitter();
    @Input() url = '';
    @Input() queryParams = '';
    @Input() viewerUrl = '';
    @Input() googleCheckInterval = 3000;
    @Input() disableContent: 'none' | 'all' | 'popout' | 'popout-hide' = 'none';
    @Input() googleCheckContentLoaded = true;
    @Input() viewer: viewerType;
    @ViewChildren('iframe') iframes: QueryList<ElementRef>;

    public fullUrl: SafeResourceUrl = null;
    public externalViewer = false;
    public docHtml = '';
    public configuredViewer: viewerType = 'google';
    private checkIFrameSubscription: Subscription = null;

    constructor(private domSanitizer: DomSanitizer, private ngZone: NgZone) { }

    ngOnDestroy(): void {
        if (this.checkIFrameSubscription) {
            this.checkIFrameSubscription.unsubscribe();
        }
    }

    async ngOnChanges(changes: SimpleChanges): Promise<void> {
        if (changes && changes.viewer && (changes.viewer.isFirstChange || changes.viewer.currentValue !== changes.viewer.previousValue)) {
            if (this.viewer !== 'google' && this.viewer !== 'office' &&
                this.viewer !== 'mammoth' && this.viewer !== 'pdf' && this.viewer !== 'url') {
                console.error(`Unsupported viewer: '${this.viewer}'. Supported viewers: google, office, mammoth and pdf`);
            }
            this.configuredViewer = this.viewer;
        }

        if ((changes.url && changes.url.currentValue !== changes.url.previousValue) ||
            changes.viewer && changes.viewer.currentValue !== changes.viewer.previousValue ||
            changes.viewerUrl && changes.viewerUrl.currentValue !== changes.viewerUrl.previousValue) {
            const viewerDetails = getViewerDetails(this.url, this.configuredViewer, this.queryParams, this.viewerUrl);
            this.externalViewer = viewerDetails.externalViewer;
            this.docHtml = '';
            if (this.checkIFrameSubscription) {
                this.checkIFrameSubscription.unsubscribe();
            }
            if (!this.url) {
                this.fullUrl = null;
            } else if (viewerDetails.externalViewer || this.configuredViewer === 'url') {
                this.fullUrl = this.domSanitizer.bypassSecurityTrustResourceUrl(viewerDetails.url);
                // see:
                // https://stackoverflow.com/questions/40414039/google-docs-viewer-returning-204-responses-no-longer-working-alternatives
                // hack to reload iframe if it's not loaded.
                // would maybe be better to use view.officeapps.live.com but seems not to work with sas token.
                if (this.configuredViewer === 'google' && this.googleCheckContentLoaded) {
                    this.ngZone.runOutsideAngular(() => {
                        // if it's not loaded after the googleIntervalCheck, then open load again.
                        const iframe = this.iframes?.first?.nativeElement;
                        this.googleCheckInterval;
                        this.checkIFrameSubscription = googleCheckSubscription(iframe, this.googleCheckInterval);
                    });
                }
            } else if (this.configuredViewer === 'mammoth') {
                this.docHtml = await getDocxToHtml(this.url);
            }
        }
    }

    iframeLoaded() {
        this.loaded.emit(null);
        if (this.checkIFrameSubscription) {
            this.checkIFrameSubscription.unsubscribe();
        }
    }
}

<ng-container *ngIf="!externalViewer">
    <div *ngIf="configuredViewer !== 'pdf'" [innerHtml]="docHtml"></div>
    <object *ngIf="fullUrl && configuredViewer === 'pdf'" [data]="fullUrl"
        type="application/pdf" width="100%" height="100%">
        <p>Your browser does not support PDFs.
            <a [href]="fullUrl">Download the PDF</a>.</p>
    </object>
</ng-container>
<ng-container *ngIf="externalViewer">
    <iframe (load)="iframeLoaded()" *ngIf="fullUrl && disableContent === 'none'" #iframe id="iframe" frameBorder="0" [src]="fullUrl"></iframe>
    <div class="container" *ngIf="disableContent !== 'none'">
        <div [class.overlay-full]="disableContent === 'all'"
            [class.overlay-popout-google]="configuredViewer ==='google' && (disableContent === 'popout' || disableContent === 'popout-hide')"
            [class.overlay-popout-office]="configuredViewer ==='office' && (disableContent === 'popout' || disableContent === 'popout-hide')"
            [style.background-color]="disableContent === 'popout-hide' ? '#fff': 'transparent'">
        </div>
        <iframe (load)="iframeLoaded()" *ngIf="fullUrl" #iframe id="iframe" frameBorder="0" [src]="fullUrl"></iframe>
    </div>
</ng-container>

// libs/ui-react/src/lib/document-viewer.tsx
import React, { useEffect, useRef, useState } from 'react';
import { Subscription, timer } from 'rxjs';
import {
  googleCheckSubscription,
  getViewerDetails,
  getDocxToHtml,
} from '@documentviewer/data';

const iframeStyle = {
  width: '100%',
  height: '100%',
};

export type viewerType = 'google' | 'office' | 'mammoth' | 'pdf' | 'url';

interface Props {
  loaded?: () => void;
  url: string;
  queryParams?: string;
  viewerUrl?: string;
  googleCheckInterval?: number;
  disableContent?: 'none' | 'all' | 'poput' | 'popout-hide';
  googleCheckContentLoaded?: boolean;
  viewer?: viewerType;
}

const defaultProps: Props = {
  // eslint-disable-next-line @typescript-eslint/no-empty-function
  loaded: () => {},
  disableContent: 'none',
  googleCheckContentLoaded: true,
  googleCheckInterval: 3000,
  queryParams: '',
  url: '',
  viewer: 'google',
  viewerUrl: '',
};

interface State {
  url: string;
  isloaded: boolean;
}

export const DocumentViewer = (props: Props) => {
  props = { ...defaultProps, ...props };
  const iframeRef = useRef(null);
  let checkIFrameSubscription: Subscription;
  const [url, setUrl] = useState('');
  const [externalViewer, setExternalViewer] = useState(true);
  const [loaded, setLoaded] = useState(false);
  const [docHtml, setDocHtml] = useState(null);

  useEffect(() => {
    const details = getViewerDetails(
      props.url,
      props.viewer,
      props.queryParams,
      props.viewerUrl
    );
    setUrl(details.url);
    setExternalViewer(details.externalViewer);
    if (iframeRef && iframeRef.current) {
      const iframe = iframeRef.current;
      // eslint-disable-next-line react-hooks/exhaustive-deps
      if (!loaded) {
        checkIFrameSubscription = googleCheckSubscription(
          iframe,
          props.googleCheckInterval
        );
      }
    } else if (props.viewer === 'mammoth') {
      const setHtml = async () => {
        setDocHtml({__html: await getDocxToHtml(url) });
      };
      setHtml();
    }
  }, [props]);

  const iframeLoaded = () => {
    props.loaded();
    if (checkIFrameSubscription) {
      checkIFrameSubscription.unsubscribe();
    }
  };

  return externalViewer ? (
    <iframe
      style={iframeStyle}
      ref={iframeRef}
      onLoad={() => {
        console.log('loaded.');
        setLoaded(true);
        iframeLoaded();
      }}
      id="iframe"
      title="iframe"
      frameBorder="0"
      src={url}
    ></iframe>
  ) : props.viewer !== 'pdf' ? (
    <div dangerouslySetInnerHTML={docHtml}></div>
  ) : (
    url ? <object data={url} type="application/pdf" width="100%" height="100%">
      <p>
        Your browser does not support PDFs.
        <a href={url}>Download the PDF</a>.
      </p>
    </object> : null
  );
};
